### ISSUE TITLE
[QA] Automated tests

### ISSUE THREAD

**Issue by ferndot** [joshua-s/coronavirus-diary#12]
We are in dire need of automated testing to ensure the app's stability.

I will be creating issues for individual components.

**Comment by aadarsh-patel** [comment]
Hey @joshua-s ,
I am having trouble running integration test `smoke_workflow.dart`.

I ran command, `flutter drive --target=test_driver/smoke_workflow.dart `
and i got the following errors,
```Using device AOSP on IA Emulator.
Starting application: test_driver/smoke_workflow.dart
Installing build\app\outputs\apk\app.apk...                         8.0s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        15.6s
√ Built build\app\outputs\apk\debug\app-debug.apk.
D/FlutterActivity(14981): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(14981): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(14981): No preferred FlutterEngine was provided. Creating a new FlutterEngine for
this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(14981): Attaching FlutterEngine to the Activity that owns this Fragment.
I/flutter (14981): Observatory listening on http://127.0.0.1:40950/xf5Hh5p2MmE=/
D/FlutterView(14981): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@fa18533
D/FlutterActivityAndFragmentDelegate(14981): Executing Dart entrypoint: main, and sending initial route: /
00:00 +0: User can reach checkup and share screen

[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:6063/xf5Hh5p2MmE=/
[trace] FlutterDriver: Isolate found with number: 3242372806874311
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[info ] FlutterDriver: Connected to Flutter application.
00:02 +0 -1: User can reach checkup and share screen [E]

  DriverError: Error in Flutter application: Uncaught extension error while executing tap: 'package:flutter_driver/src/extension/extension.dart': Failed assertion: line 202 pos 14: 'WidgetsBinding.instance.isRootWidgetAttached || !command.requiresRootWidgetAttached': No root widget is attached; have you remembered to call runApp()?
  #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
  #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
  #2      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:202:14)
  #3      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:518:32)
  <asynchronous suspension>
  #4      _runExtension (dart:developer-patch/developer.dart:86:23)

  Original error: null
  Original stack trace:
  null


  package:flutter_driver/src/driver/driver.dart 456:7           FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1064:19                                  _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 82:23                       _asyncErrorWrapperHelper
  package:test_api/src/backend/invoker.dart                     Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:test_api/src/backend/invoker.dart 239:5               Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/declarer.dart 169:33             Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:test_api/src/backend/declarer.dart 168:13             Declarer.test.<fn>
  package:test_api/src/backend/invoker.dart 392:25              Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 176:37                                 new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122:38                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 949:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 23:15                       Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 384:19                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 418:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 174:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 964:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 54:45                                   new Timer
  dart:async/timer.dart 91:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test_api/src/backend/invoker.dart 391:21              Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:test_api/src/backend/invoker.dart 378:9               Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 430:15              Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 377:7               Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101:24                     Chain.capture.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:stack_trace/src/chain.dart 99:12                      Chain.capture
  package:test_api/src/backend/invoker.dart 376:11              Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 185:5  LiveTestController._run
  package:test_api/src/backend/live_test_controller.dart 40:37  _LiveTest.run
  dart:async/future.dart 202:37                                 new Future.microtask.<fn>
  dart:async/zone.dart 1122:38                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 43:21                      _microtaskLoop
  dart:async/schedule_microtask.dart 52:5                       _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                  _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 175:5                   _RawReceivePortImpl._handleMessage


00:02 +0 -1: User can go back from the checkup screen to home

[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:6063/xf5Hh5p2MmE=/
[trace] FlutterDriver: Isolate found with number: 3242372806874311
[trace] FlutterDriver: Isolate is not paused. Assuming application is ready.
[info ] FlutterDriver: Connected to Flutter application.
[warning] FlutterDriver: tap message is taking a long time to complete...
00:32 +0 -2: User can go back from the checkup screen to home [E]

  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds.

  package:test_api/src/backend/invoker.dart 324:28              Invoker._handleError.<fn>
  dart:async/zone.dart 1122:38                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  package:test_api/src/backend/invoker.dart 322:10              Invoker._handleError
  package:test_api/src/backend/invoker.dart 275:9               Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  package:test_api/src/backend/invoker.dart 273:38              Invoker.heartbeat.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 949:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 23:15                       Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 384:19                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 418:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 174:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 948:22                                   _CustomZone.bindCallback
  dart:async/zone.dart 1193:21                                  _rootCreateTimer
  dart:async/zone.dart 1090:19                                  _CustomZone.createTimer
  package:test_api/src/backend/invoker.dart 272:34              Invoker.heartbeat
  package:test_api/src/backend/invoker.dart 235:5               Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/declarer.dart 169:33             Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:test_api/src/backend/declarer.dart 168:13             Declarer.test.<fn>
  package:test_api/src/backend/invoker.dart 392:25              Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 176:37                                 new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122:38                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 949:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 23:15                       Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 384:19                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 418:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 174:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 964:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 54:45                                   new Timer
  dart:async/timer.dart 91:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test_api/src/backend/invoker.dart 391:21              Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:test_api/src/backend/invoker.dart 378:9               Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 430:15              Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 377:7               Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101:24                     Chain.capture.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:stack_trace/src/chain.dart 99:12                      Chain.capture
  package:test_api/src/backend/invoker.dart 376:11              Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 185:5  LiveTestController._run
  package:test_api/src/backend/live_test_controller.dart 40:37  _LiveTest.run
  dart:async/future.dart 202:37                                 new Future.microtask.<fn>
  dart:async/zone.dart 1122:38                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 43:21                      _microtaskLoop
  dart:async/schedule_microtask.dart 52:5                       _startMicrotaskLoop
  dart:isolate-patch/timer_impl.dart 393:30                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 418:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 174:12                  _RawReceivePortImpl._handleMessage


  DriverError: Failed to fulfill Tap due to remote error
  Original error: Bad state: The client closed with pending request "ext.flutter.driver".
  Original stack trace:
  #0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
  #1      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #2      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #3      _rootRun (dart:async/zone.dart:1122:38)
  #4      _CustomZone.run (dart:async/zone.dart:1023:19)
  #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:163:18)
  #6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:650:39)
  #7      Future._propagateToListeners (dart:async/future_impl.dart:706:37)
  #8      Future._propagateToListeners (dart:async/future_impl.dart:607:9)
  #9      Future._completeWithValue (dart:async/future_impl.dart:524:5)
  #10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
  #11     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #12     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #13     _rootRun (dart:async/zone.dart:1126:13)
  #14     _CustomZone.run (dart:async/zone.dart:1023:19)
  #15     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
  #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
  #17     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
  #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
  #19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
  #20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
  #21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)



  package:flutter_driver/src/driver/driver.dart 449:7           FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1064:19                                  _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 82:23                       _asyncErrorWrapperHelper
  package:test_api/src/backend/invoker.dart                     Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:test_api/src/backend/invoker.dart 239:5               Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/declarer.dart 169:33             Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:test_api/src/backend/declarer.dart 168:13             Declarer.test.<fn>
  package:test_api/src/backend/invoker.dart 392:25              Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 176:37                                 new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122:38                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 949:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 23:15                       Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 384:19                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 418:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 174:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 964:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 54:45                                   new Timer
  dart:async/timer.dart 91:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test_api/src/backend/invoker.dart 391:21              Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:test_api/src/backend/invoker.dart 378:9               Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 430:15              Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 377:7               Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101:24                     Chain.capture.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:stack_trace/src/chain.dart 99:12                      Chain.capture
  package:test_api/src/backend/invoker.dart 376:11              Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 185:5  LiveTestController._run
  package:test_api/src/backend/live_test_controller.dart 40:37  _LiveTest.run
  dart:async/future.dart 202:37                                 new Future.microtask.<fn>
  dart:async/zone.dart 1122:38                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 43:21                      _microtaskLoop
  dart:async/schedule_microtask.dart 52:5                       _startMicrotaskLoop
  dart:isolate-patch/timer_impl.dart 393:30                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 418:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 174:12                  _RawReceivePortImpl._handleMessage


00:33 +0 -2: User can checkup on their health

00:33 +0 ~1 -2: User can tap on delete data and back to the first page

[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:6063/xf5Hh5p2MmE=/
[trace] FlutterDriver: Isolate found with number: 3242372806874311
[trace] FlutterDriver: Isolate is not paused. Assuming application is ready.
[info ] FlutterDriver: Connected to Flutter application.
[warning] FlutterDriver: tap message is taking a long time to complete...```

**Comment by ferndot** [comment]
@jonahwilliams do you have any ideas as to what could be causing this ^

**Comment by aadarsh-patel** [comment]
I am not sure but I think integration tests `smoke_workflow_test.dart` is currently just a blueprint of tests to be performed with some dummy data.

Because the string value of 
`final learnMoreButton = find.text('Click here to learn more');`  in test

```dart
RaisedButton(
        onPressed: () => {
          Provider.of<PageController>(context, listen: false)
                .nextPage(
                  duration: Duration(milliseconds: 400),
                  curve: Curves.easeInOut,
                  )
               },
              child: Text(localizations.tutorialIntroStepLearnMore),
          ),
```

does not match up with the value present in the `app_localizations_en.dart`
i.e. ` String get tutorialIntroStepLearnMore => 'LEARN MORE';`

If that is the case then I would be happy to work on this issue.

**Comment by ferndot** [comment]
@aadarsh-patel thanks for your patience. Apparently, this smoke test has been breaking for a while and is not up to date with the current state of the app.

**Comment by christopherfujino** [comment]
It hasn't been running on pre-submit, I'm currently working on getting that back.

**Comment by christopherfujino** [comment]
Should be running on pre-submit now.

**Comment by ferndot** [comment]
Since the testing infrastructure has been configured and is running successfully, this issue can be resolved! Further automated testing fixes/improvements can be placed in new issues.
